name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_FRONT: front-despacho
  ECR_BACK_VENTAS: api-ventas
  ECR_BACK_DESPACHO: api-despacho
  ECS_CLUSTER: cluster-innovatech

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --- FRONTEND ---
    - name: Build y Push Frontend
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONT }}:latest -f front_despacho/Dockerfile ./front_despacho
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONT }}:latest

    # --- BACKEND VENTAS ---
    - name: Build y Push Backend Ventas
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACK_VENTAS }}:latest -f Springboot-API-REST/Dockerfile ./Springboot-API-REST
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACK_VENTAS }}:latest

    # --- BACKEND DESPACHO ---
    - name: Build y Push Backend Despacho
      run: |
        docker build --build-arg REACT_APP_API_URL=http://98.80.5.102:8082 -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONT }}:latest -f front_despacho/Dockerfile ./front_despacho
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONT }}:latest

    # --- REFRESH SERVICIOS ECS ---
    - name: Forzar despliegue servicios
      run: |
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service servicio-front --force-new-deployment
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service servicio-ventas --force-new-deployment
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service servicio-despacho --force-new-deployment
