name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_FRONT_REPO: front-despacho
  ECR_BACK_REPO: api-despacho
  ECS_CLUSTER: cluster-innovatech
  ECS_SERVICE_FRONT: servicio-front
  ECS_SERVICE_BACK: servicio-despacho

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --- DESPLIEGUE FRONTEND ---
    - name: Build y Push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_FRONT_REPO:latest -f front_despacho/Dockerfile ./front_despacho
        docker push $ECR_REGISTRY/$ECR_FRONT_REPO:latest

    # --- DESPLIEGUE BACKEND ---
    - name: Build y Push Backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_BACK_REPO:latest -f Springboot-API-REST/Dockerfile ./Springboot-API-REST
        docker push $ECR_REGISTRY/$ECR_BACK_REPO:latest

    # --- ACTUALIZAR SERVICIOS EN ECS ---
    - name: Forzar nuevo despliegue en ECS
      run: |
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_FRONT }} --force-new-deployment
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE_BACK }} --force-new-deployment
